2020-01-28 14:43:14,846 DEBUG   MainThread:32731 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2020-01-28 14:43:14,864 DEBUG   MainThread:32731 [cmd.py:execute():728] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/clemens/repositorys/pytorch-ai, universal_newlines=False, shell=None, istream=<valid stream>)
2020-01-28 14:43:14,877 DEBUG   MainThread:32731 [cmd.py:execute():728] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/clemens/repositorys/pytorch-ai, universal_newlines=False, shell=None, istream=None)
2020-01-28 14:43:14,887 DEBUG   MainThread:32731 [cmd.py:execute():728] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/clemens/repositorys/pytorch-ai, universal_newlines=False, shell=None, istream=None)
2020-01-28 14:43:14,906 DEBUG   MainThread:32731 [run_manager.py:__init__():535] Initialized sync for tictactoe/mvx4evw0
2020-01-28 14:43:14,912 INFO    MainThread:32731 [run_manager.py:wrap_existing_process():1133] wrapping existing process 32725
2020-01-28 14:43:14,913 WARNING MainThread:32731 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-01-28 14:43:14,919 DEBUG   MainThread:32731 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): pypi.org:443
2020-01-28 14:43:15,060 DEBUG   MainThread:32731 [connectionpool.py:_make_request():393] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 39767
2020-01-28 14:43:15,179 INFO    MainThread:32731 [run_manager.py:init_run():918] system metrics and metadata threads started
2020-01-28 14:43:15,181 INFO    MainThread:32731 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2020-01-28 14:43:15,183 INFO    MainThread:32731 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2020-01-28 14:43:15,862 INFO    Thread-3  :32731 [run_manager.py:_on_file_modified():682] file/dir modified: /home/clemens/repositorys/pytorch-ai/TicTacToe_AI/Net/wandb/dryrun-20200128_134313-mvx4evw0/config.yaml
2020-01-28 14:43:32,850 INFO    MainThread:32731 [run_manager.py:_sync_etc():1313] process received interrupt signal, shutting down
2020-01-28 14:43:32,850 INFO    MainThread:32731 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2020-01-28 14:43:32,851 INFO    MainThread:32731 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
  MainThread:32731 [mvx4evw0:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2020-01-28 14:43:32,851 INFO    MainThread:32731 [mvx4evw0:run_manager.py:shutdown():1057] shutting down system stats and metadata service
